# Alacritty configuration
# https://alacritty.org/config-alacritty.html

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16.0

[general]
live_config_reload = true

[window]
opacity = 0.9
blur = true
dynamic_title = true
option_as_alt = "Both"

[keyboard]
bindings = [
  { key = "N", mods = "Command", action = "None" },
]
